# Learning Tensors

In [25]:
import torch
import numpy as np
import gc

## Initialize a Tensor

In [11]:
# from list data 
list_data = [[1,2], [3,4]]
tensor_from_list = torch.tensor(list_data)
print(tensor_from_list)

# from numpy
np_data = np.array(list_data)
tensor_from_np = torch.from_numpy(np_data)
print(tensor_from_np)

# specify dtype
tensor_from_list_int32 = torch.tensor(list_data, dtype=torch.int32)
print(tensor_from_list_int32)

# from others (param type must be torch.Tensor)
tensor_ones = torch.ones_like(tensor_from_list)
print(f"Ones like: \n{tensor_ones}")

tensor_rand = torch.rand_like(tensor_from_list, dtype=torch.float)
print(f"Rand like: \n{tensor_rand}")

# clear


tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
Ones like: 
tensor([[1, 1],
        [1, 1]])
Rand like: 
tensor([[0.7769, 0.1251],
        [0.8057, 0.9650]])


In [13]:
# from shape

shape = (3, 4, ) # why comma
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor}")
print(f"Ones Tensor: \n {ones_tensor}")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6531, 0.5625, 0.1387, 0.1842],
        [0.2118, 0.7784, 0.2184, 0.6342],
        [0.8886, 0.9023, 0.7651, 0.4538]])
Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## Tensor Attribute

- shape
- dtype
- device

In [14]:
print(f"Shape: {tensor_from_list.shape}")
print(f"Dtype: {tensor_from_list.dtype}")
print(f"Device: {tensor_from_list.device}")

Shape: torch.Size([2, 2])
Dtype: torch.int64
Device: cpu


## Tensor Operation

- indexing and slicing
- joining
- arithmetic
- single element value
- in-place

In [31]:
tensor_test = torch.rand((4, 5))
print(f"Origin Matrix: \n{tensor_test}\n")
# indexing
# tensor[i][j] -> Row i, Col j
print(f"Row 1, Col 1: {tensor_test[1][1]}\n")

# slicing
print(f"Col 0: {tensor_test[:, 0]}")
print(f"Row 0: {tensor_test[0, :]}")
print(f"Col 1: {tensor_test[..., 1]}")
print(f"Row 1: {tensor_test[1, ...]}\n")

# joining
tensors = [torch.rand((3,4)) for i in range(3)]
tensor_concat = torch.cat(tensors, dim=0)
print(f"Concat on Dimension 0: \n{tensor_concat.shape}")
tensor_concat = torch.cat(tensors, dim=1)
print(f"Concat on Dimension 1: \n{tensor_concat.shape}\n")


Origin Matrix: 
tensor([[0.1028, 0.5712, 0.5159, 0.6558, 0.3224],
        [0.4245, 0.9658, 0.2291, 0.5656, 0.7840],
        [0.6976, 0.6045, 0.4621, 0.0453, 0.2933],
        [0.8619, 0.8914, 0.5669, 0.7054, 0.2762]])
Row 1, Col 1: 0.965757429599762
Col 0: tensor([0.1028, 0.4245, 0.6976, 0.8619])
Row 0: tensor([0.1028, 0.5712, 0.5159, 0.6558, 0.3224])
Col 1: tensor([0.5712, 0.9658, 0.6045, 0.8914])
Row 1: tensor([0.4245, 0.9658, 0.2291, 0.5656, 0.7840])

Concat on Dimension 0: 
torch.Size([9, 4])
Concat on Dimension 1: 
torch.Size([3, 12])
