# Learning Tensors

In [25]:
import torch
import numpy as np
import gc

## Initialize a Tensor

In [11]:
# from list data 
list_data = [[1,2], [3,4]]
tensor_from_list = torch.tensor(list_data)
print(tensor_from_list)

# from numpy
np_data = np.array(list_data)
tensor_from_np = torch.from_numpy(np_data)
print(tensor_from_np)

# specify dtype
tensor_from_list_int32 = torch.tensor(list_data, dtype=torch.int32)
print(tensor_from_list_int32)

# from others (param type must be torch.Tensor)
tensor_ones = torch.ones_like(tensor_from_list)
print(f"Ones like: \n{tensor_ones}")

tensor_rand = torch.rand_like(tensor_from_list, dtype=torch.float)
print(f"Rand like: \n{tensor_rand}")

# clear


tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
Ones like: 
tensor([[1, 1],
        [1, 1]])
Rand like: 
tensor([[0.7769, 0.1251],
        [0.8057, 0.9650]])


In [13]:
# from shape

shape = (3, 4, ) # why comma
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor}")
print(f"Ones Tensor: \n {ones_tensor}")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6531, 0.5625, 0.1387, 0.1842],
        [0.2118, 0.7784, 0.2184, 0.6342],
        [0.8886, 0.9023, 0.7651, 0.4538]])
Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## Tensor Attribute

- shape
- dtype
- device

In [14]:
print(f"Shape: {tensor_from_list.shape}")
print(f"Dtype: {tensor_from_list.dtype}")
print(f"Device: {tensor_from_list.device}")

Shape: torch.Size([2, 2])
Dtype: torch.int64
Device: cpu


## Tensor Operation

- indexing and slicing
- joining
- arithmetic
- single element value
- in-place

In [49]:
tensor_test = torch.rand((4, 5))
print(f"Origin Matrix: \n{tensor_test}\n")
# indexing
# tensor[i][j] -> Row i, Col j
print(f"Row 1, Col 1: {tensor_test[1][1]}\n")

# slicing
print(f"Col 0: {tensor_test[:, 0]}")
print(f"Row 0: {tensor_test[0, :]}")
print(f"Col 1: {tensor_test[..., 1]}")
print(f"Row 1: {tensor_test[1, ...]}\n")

# joining
tensors = [torch.rand((3,4)) for i in range(3)]
tensor_concat = torch.cat(tensors, dim=0)
print(f"Concat on Dimension 0: \n{tensor_concat.shape}")
tensor_concat = torch.cat(tensors, dim=1)
print(f"Concat on Dimension 1: \n{tensor_concat.shape}\n")

# arithmetic
tensor_test = torch.rand((5,5))
print(f"Origin Matrix: \n{tensor_test}\n")
## matmul
res1 = tensor_test @ tensor_test.T
res2 = tensor_test.matmul(tensor_test.T)
res3 = torch.zeros_like(tensor_test)
torch.matmul(tensor_test, tensor_test.T, out=res3)
print(res1.equal(res2) and res2.equal(res3))
## element-wise mul
res1 = tensor_test * tensor_test
res2 = tensor_test.mul(tensor_test)
res3 = torch.zeros_like(tensor_test)
torch.mul(tensor_test, tensor_test, out=res3)
print(res1.equal(res2) and res2.equal(res3))

Origin Matrix: 
tensor([[0.6203, 0.0910, 0.4930, 0.3318, 0.6971],
        [0.4887, 0.6994, 0.8309, 0.2498, 0.5891],
        [0.5998, 0.6979, 0.9462, 0.4678, 0.2603],
        [0.2270, 0.7898, 0.9122, 0.0363, 0.0032]])

Row 1, Col 1: 0.6994019150733948

Col 0: tensor([0.6203, 0.4887, 0.5998, 0.2270])
Row 0: tensor([0.6203, 0.0910, 0.4930, 0.3318, 0.6971])
Col 1: tensor([0.0910, 0.6994, 0.6979, 0.7898])
Row 1: tensor([0.4887, 0.6994, 0.8309, 0.2498, 0.5891])

Concat on Dimension 0: 
torch.Size([9, 4])
Concat on Dimension 1: 
torch.Size([3, 12])

Origin Matrix: 
tensor([[0.8225, 0.9529, 0.3422, 0.7293, 0.9728],
        [0.7853, 0.3901, 0.2475, 0.0076, 0.5201],
        [0.2385, 0.8764, 0.6028, 0.0901, 0.5250],
        [0.5516, 0.6639, 0.4055, 0.5663, 0.1659],
        [0.4973, 0.9315, 0.9401, 0.3427, 0.4079]])

True
True


## Single element

In [51]:
tensor_sum = tensor_test.sum()
print(type(tensor_sum))
print(type(tensor_sum.item()))

<class 'torch.Tensor'>
<class 'float'>


## In-place

In [53]:
print(f"Origin Matrix: \n{tensor_test}\n")
# add to every element
tensor_test.add_(5)
print(f"Current Matrix: \n{tensor_test}\n")


Origin Matrix: 
tensor([[0.8225, 0.9529, 0.3422, 0.7293, 0.9728],
        [0.7853, 0.3901, 0.2475, 0.0076, 0.5201],
        [0.2385, 0.8764, 0.6028, 0.0901, 0.5250],
        [0.5516, 0.6639, 0.4055, 0.5663, 0.1659],
        [0.4973, 0.9315, 0.9401, 0.3427, 0.4079]])

Current Matrix: 
tensor([[5.8225, 5.9529, 5.3422, 5.7293, 5.9728],
        [5.7853, 5.3901, 5.2475, 5.0076, 5.5201],
        [5.2385, 5.8764, 5.6028, 5.0901, 5.5250],
        [5.5516, 5.6639, 5.4055, 5.5663, 5.1659],
        [5.4973, 5.9315, 5.9401, 5.3427, 5.4079]])

